---
- name: Install Apache HTTPD on EC2 instances and deploy static webpage
  hosts: WebServer
  become: true
  gather_facts: yes  
  vars:
    ansible_ssh_common_args: "-o ProxyCommand='ssh -i ~/.ssh/acs730-final-proj -W %h:%p ec2-user@{{ hostvars[groups['tag_Bastion_WebServer'][0]].public_ip_address }}'"
  tasks:
    - name: Install HTTPD
      yum:
        name: httpd
        state: present

    - name: Create a static HTML file with IP address
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
            <head><title>My Static Webpage</title></head>
            <body>
              <h1>Welcome to My Static Webpage!</h1>
              <p>This is a static webpage served by Apache HTTPD on EC2. This is group project of Ven and Sushmita.</p>
              <p><strong>Server Public IP:</strong> {{ ansible_host }}</p>
            </body>
          </html>
        owner: apache
        group: apache
        mode: '0644'

    - name: Start and enable HTTPD
      systemd:
        name: httpd
        state: started
        enabled: true
