name: Lint and Run Ansible Playbook

on:
  push:
    branches: [staging, prod]
  pull_request:
    branches: [staging, prod]

jobs:
  ansible:
    name: Lint and Execute Ansible
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint boto3 botocore
          ansible-galaxy collection install amazon.aws

      - name: Run ansible-lint
        run: ansible-lint .

      - name: Set up SSH Private Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/acs730-final-proj
          chmod 600 ~/.ssh/acs730-final-proj
        shell: bash

      - name: Configure Ansible
        run: |
          cat > ansible.cfg <<EOF
          [defaults]
          inventory = ./aws_ec2.yaml
          remote_user = ec2-user
          private_key_file = ~/.ssh/acs730-final-proj
          host_key_checking = False
          EOF

      # Optional: Debug dynamic inventory
      - name: Debug EC2 Inventory
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: ansible-inventory -i aws_ec2.yaml --list

      - name: Run Ansible Playbook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          export AWS_REGION=us-east-1
          ansible-playbook playbook.yaml
