name: Lint and Run Ansible Playbook

on:
  push:
    branches:
      - staging
      - prod
  pull_request:
    branches:
      - staging
      - prod

jobs:
  ansible:
    name: Lint and Execute Ansible
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint boto3 botocore
          ansible-galaxy collection install amazon.aws

      - name: Run ansible-lint
        run: |
          ansible-lint .

      - name: Set up AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          echo "AWS credentials configured."

      - name: Run Ansible Playbook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          ansible-playbook -i aws_ec2.yaml playbook.yaml
